[package]
name = "infarter"
version = "0.1.0"
authors = ["papanumba"]
edition = "2021"
description = "DryFart interpreter"
repository = "https://github.com/papanumba/dryfart"
license = "GPL-3.0"

[profile.release]
lto = true
strip = true
#panic = "abort"
#debug = false
